"""added user jobs and comment functionality

Revision ID: bd2f85c198aa
Revises: 0a82e6d69392
Create Date: 2026-01-30 13:56:58.331876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2f85c198aa'
down_revision = '0a82e6d69392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
